from pathlib import Path

MODEL_DIR = Path("models")
IMAGES_DIR = Path("input_images")

CNN_MODEL = MODEL_DIR / "cnn/vfn/final/best_model_cnn2.pth"
YOLO_MODEL = MODEL_DIR / "yolo/v2/best.pt"

FOOD_CLASSES = (
    "almonds",
    "apple",
    "apple_pie",
    "apple_sauce",
    "avocado",
    "bacon",
    "bagel",
    "baked_beans",
    "baked_potato",
    "bananas",
    "beer",
    "biscuit",
    "black_beans",
    "blueberries",
    "boiled_egg",
    "breaded_fish",
    "broccoli",
    "brown_rice",
    "brownie",
    "burrito",
    "cabbage",
    "cake",
    "cantaloupe",
    "carrot",
    "cheese_burger",
    "cheese_sandwiches",
    "chicken_breast",
    "chicken_nugget",
    "chicken_tender",
    "chicken_thigh",
    "chicken_wing",
    "chips",
    "chocolate_milk",
    "cinnamon_bun",
    "coleslaw",
    "cookie",
    "corn",
    "cornbread",
    "croissant",
    "cupcake",
    "doughnut",
    "french_fries",
    "french_toast",
    "fried_egg",
    "fried_rice",
    "fruit_drink",
    "green_beans",
    "grilled_salmon",
    "hash_brown",
    "hot_dog",
    "ice_cream",
    "lasagna",
    "mac_and_cheese",
    "mashed_potatoes",
    "meat_loaf",
    "milk",
    "muffin",
    "omelet",
    "pancake",
    "pasta",
    "pizza",
    "pork_chop",
    "pork_rib",
    "quesadilla",
    "red_wine",
    "shrimp",
    "soup",
    "steak",
    "stew_beef",
    "strawberries",
    "sushi",
    "taco",
    "tomatoes",
    "tortillas",
    "tostada",
    "tuna_salad",
    "turkey",
    "waffle",
    "white_rice",
    "white_wine",
    "yeast_bread",
    "yogurt",
)


